<?php

/**
 * @var CristianScheid\WeatherWidget\Block\WeatherWidget $block
 */

$isModuleEnabled = $block->isModuleEnabled();
$lastConfigChange = $block->getLastConfigChange();
?>

<script type="text/x-magento-init">
  {
    "*": {
      "CristianScheid_WeatherWidget/js/weather-widget": {
        "isModuleEnabled": "<?= $isModuleEnabled ?>",
        "lastConfigChange": "<?= $lastConfigChange ?>"
      }
    }
  }
</script>